INSERT INTO car (brand, year, color) VALUES
  ('Audi', 1992, 'Red'),
  ('Fiat', 2001, 'Red'),
  ('Mercedes', 1991, 'Brown'),
  ('Fiat', 1962, 'Black'),
  ('Renault', 1997, 'Brown'),
  ('Renault', 1967, 'Maroon'),
  ('Renault', 1986, 'Yellow'),
  ('BMW', 1970, 'Maroon'),
  ('Fiat', 1990, 'Silver'),
  ('Renault', 1972, 'Black');
  

  
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Elon Musk', 'United States', 'Technology', '1', '291995088681') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jeff Bezos', 'United States', 'Technology', '2', '196322363191') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Bernard Arnault', 'France', 'Consumer', '3', '164058278153') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Bill Gates', 'United States', 'Technology', '4', '134710657190') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Larry Page', 'United States', 'Technology', '5', '129695907266') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sergey Brin', 'United States', 'Technology', '6', '125073117581') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mark Zuckerberg', 'United States', 'Technology', '7', '116640683479') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Steve Ballmer', 'United States', 'Technology', '8', '115227932386') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Larry Ellison', 'United States', 'Technology', '9', '114068649694') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Warren Buffett', 'United States', 'Diversified', '10', '104642501393') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mukesh Ambani', 'India', 'Energy', '11', '99141175261') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Francoise Bettencourt Meyers', 'France', 'Consumer', '12', '89287043078') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gautam Adani', 'India', 'Industrial', '13', '79208720537') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Amancio Ortega', 'Spain', 'Retail', '14', '76576397948') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhong Shanshan', 'China', 'Diversified', '15', '65997096889') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jim Walton', 'United States', 'Retail', '16', '65881585225') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Rob Walton', 'United States', 'Retail', '17', '65452804926') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Carlos Slim', 'Mexico', 'Diversified', '18', '64298993332') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alice Walton', 'United States', 'Retail', '19', '64034488561') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Charles Koch', 'United States', 'Industrial', '20', '61790548914') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Julia Flesher Koch & family', 'United States', 'Industrial', '21', '61790548914') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Phil Knight & family', 'United States', 'Consumer', '22', '61103279920') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'MacKenzie Scott', 'United States', 'Technology', '23', '57279655877') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Michael Dell', 'United States', 'Technology', '24', '55312006786') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zeng Yuqun', 'Hong Kong', 'Industrial', '25', '55286060487') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Francois Pinault', 'France', 'Consumer', '26', '50313935539') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ma Huateng', 'China', 'Technology', '27', '49743407196') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jacqueline Badger Mars', 'United States', 'Food & Beverage', '28', '48164060046') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Mars', 'United States', 'Food & Beverage', '29', '48164060046') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Len Blavatnik', 'United States', 'Diversified', '30', '44650067198') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhang Yiming', 'China', 'Technology', '31', '44500000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jack Ma', 'China', 'Technology', '32', '43663700781') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stephen Schwarzman', 'United States', 'Finance', '33', '39316549838') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Azim Premji', 'India', 'Technology', '34', '38658032219') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Klaus-Michael Kuehne', 'Germany', 'Industrial', '35', '35651279825') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Giovanni Ferrero & family', 'Italy', 'Food & Beverage', '36', '34429322525') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tadashi Yanai', 'Japan', 'Retail', '37', '33875111335') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Leonid Mikhelson', 'Russian Federation', 'Energy', '38', '33627103341') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Leonard Lauder', 'United States', 'Consumer', '39', '33619803293') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Takemitsu Takizaki', 'Japan', 'Technology', '40', '32603871164') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Colin Huang', 'China', 'Technology', '41', '32526320285') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pallonji Mistry', 'Ireland', 'Industrial', '42', '32473785114') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'William Ding', 'China', 'Technology', '43', '32182521000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vladimir Potanin', 'Russian Federation', 'Commodities', '44', '32030770524') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Li Ka-shing', 'Hong Kong', 'Real Estate', '45', '31229839728') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Leonardo Del Vecchio', 'Italy', 'Consumer', '46', '31163903247') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dieter Schwarz', 'Germany', 'Retail', '47', '30392663598') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alain Wertheimer', 'France', 'Consumer', '48', '30293195106') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gerard Wertheimer', 'France', 'Consumer', '49', '30293195106') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Li Shu Fu', 'China', 'Industrial', '50', '29906803069') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'He Xiangjian', 'China', 'Consumer', '51', '29180667483') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alexey Mordashov', 'Russian Federation', 'Industrial', '52', '29145423657') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Shiv Nadar', 'India', 'Technology', '53', '29082529455') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vladimir Lisin', 'Russian Federation', 'Industrial', '54', '29006486229') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dan Gilbert', 'United States', 'Real Estate', '55', '28825408664') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Eric Schmidt', 'United States', 'Technology', '56', '27844774994') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Miriam Adelson', 'United States', 'Entertainment', '57', '27461559847') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wei Jianjun', 'China', 'Consumer', '58', '27292317296') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Yang Huiyan', 'China', 'Real Estate', '59', '27067366853') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Abigail Johnson', 'United States', 'Finance', '60', '27058697265') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Chuan-Fu', 'China', 'Consumer', '61', '26811557791') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dustin Moskovitz', 'United States', 'Technology', '62', '26747961558') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'James Simons', 'United States', 'Finance', '63', '25975000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Scott Farquhar', 'Australia', 'Technology', '64', '25008511499') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mike Cannon-Brookes', 'Australia', 'Technology', '65', '25008511499') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vagit Alekperov', 'Russian Federation', 'Energy', '66', '24926072858') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Radhakishan Damani', 'India', 'Retail', '67', '24734502685') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pang Kang', 'China', 'Food & Beverage', '68', '24633146498') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Henry Cheng', 'Hong Kong', 'Retail', '69', '24419732760') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gennady Timchenko', 'Russian Federation', 'Diversified', '70', '23677488277') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Huang Shilin', 'China', 'Industrial', '71', '23579434067') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'James Dyson', 'United Kingdom', 'Consumer', '72', '23494948685') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Masayoshi Son', 'Japan', 'Technology', '73', '23316747680') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Susanne Klatten', 'Germany', 'Industrial', '74', '23308314074') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lukas Walton', 'United States', 'Retail', '75', '22850536172') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Thomas Peterffy', 'United States', 'Finance', '76', '22812666972') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lee Shau Kee', 'Hong Kong', 'Real Estate', '77', '22794921261') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Carl Icahn', 'United States', 'Diversified', '78', '22618569563') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jensen Huang', 'United States', 'Technology', '79', '22566758840') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Menard', 'United States', 'Retail', '80', '22394946814') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lakshmi Mittal', 'India', 'Commodities', '81', '22174064414') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Thomas Frist', 'United States', 'Health Care', '82', '22119247270') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Qin Yinglin', 'China', 'Food & Beverage', '83', '21751713431') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alisher Usmanov', 'Russian Federation', 'Diversified', '84', '21743195806') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Thomas Struengmann', 'Germany', 'Health Care', '85', '21652089393') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andreas Struengmann', 'Germany', 'Health Care', '86', '21652089393') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stefan Quandt', 'Germany', 'Industrial', '87', '21511334268') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ken Griffin', 'United States', 'Finance', '88', '21268208450') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Elaine Marshall', 'United States', 'Industrial', '89', '21238311728') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ernesto Bertarelli & family', 'Switzerland', 'Diversified', '90', '21103913458') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhang Zhidong', 'China', 'Technology', '91', '21022834000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Iris Fontbona & family', 'Chile', 'Commodities', '92', '20976778411') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jorge Paulo Lemann', 'Brazil', 'Food & Beverage', '93', '20733629354') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stefan Persson', 'Sweden', 'Retail', '94', '20463564207') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Forrest Li', 'Singapore', 'Technology', '95', '20296799894') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Li Xiting', 'Singapore', 'Health Care', '96', '20142579838') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Xing', 'China', 'Technology', '97', '19990513069') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Peter Woo', 'Hong Kong', 'Real Estate', '98', '19878259966') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Donald Newhouse', 'United States', 'Media & Telecom', '99', '19868711674') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jiang Rensheng', 'China', 'Health Care', '100', '19600961192') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gustaf Douglas & family', 'Sweden', 'Diversified', '101', '19582579982') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lei Jun', 'China', 'Technology', '102', '19297475529') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Aliko Dangote', 'Nigeria', 'Industrial', '103', '19240041353') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Robert Kuok', 'Malaysia', 'Diversified', '104', '19166964897') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Roman Abramovich', 'Russian Federation', 'Diversified', '105', '19035946309') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Laurene Powell Jobs', 'United States', 'Media & Telecom', '106', '18952763266') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Viktor Vekselberg', 'Russian Federation', 'Industrial', '107', '18754045483') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Budi Hartono', 'Indonesia', 'Diversified', '108', '18731905114') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sara Mota de Larrea & family', 'Mexico', 'Commodities', '109', '18682093621') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andrey Melnichenko', 'Russian Federation', 'Industrial', '110', '18529229422') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Richard Liu', 'China', 'Technology', '111', '18216545152') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jay Chaudhry', 'United States', 'Technology', '112', '18145499122') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Xu Hang', 'Hong Kong', 'Health Care', '113', '17927959984') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Wei', 'China', 'Services', '114', '17910535217') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gina Rinehart', 'Australia', 'Commodities', '115', '17778328807') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Michael Hartono', 'Indonesia', 'Diversified', '116', '17664736375') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ernie Garcia', 'United States', 'Consumer', '117', '17644257104') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Uday Kotak', 'India', 'Finance', '118', '17575147768') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alwaleed Bin Talal', 'Saudi Arabia', 'Diversified', '119', '17500648567') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dave Duffield', 'United States', 'Technology', '120', '17220612955') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Eduardo Saverin', 'Brazil', 'Technology', '121', '16937264068') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Donald Bren', 'United States', 'Real Estate', '122', '16761743062') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andrew Forrest', 'Australia', 'Commodities', '123', '16600648045') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Chen Bang', 'China', 'Health Care', '124', '16314108320') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Hasso Plattner', 'Germany', 'Technology', '125', '16286791693') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Cyrus Poonawalla', 'India', 'Health Care', '126', '16174580416') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vicky Safra', 'Greece', 'Finance', '127', '16158000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Karl Albrecht Jr', 'Germany', 'Retail', '128', '16082673958') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Beate Heister', 'Germany', 'Retail', '129', '16082673958') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Charlene de Carvalho-Heineken', 'Netherlands', 'Food & Beverage', '130', '16062017292') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ned Johnson III', 'United States', 'Finance', '131', '15955161004') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jim Goodnight', 'United States', 'Technology', '132', '15821953679') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ray Dalio', 'United States', 'Finance', '133', '15570000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Charoen Sirivadhanabhakdi', 'Thailand', 'Food & Beverage', '134', '15265701327') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mikhail Fridman', 'Russian Federation', 'Diversified', '135', '15191139785') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pei Zhenhua', 'China', 'Industrial', '136', '15097571195') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lv Xiang-yang', 'China', 'Consumer', '137', '15057287891') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dietrich Mateschitz', 'Austria', 'Food & Beverage', '138', '14929603013') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Wenyin', 'China', 'Commodities', '139', '14918351534') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'David Tepper', 'United States', 'Finance', '140', '14869000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jim Ratcliffe', 'United Kingdom', 'Industrial', '141', '14841757770') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ma Jianrong', 'China', 'Consumer', '142', '14770164211') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Harold Hamm', 'United States', 'Energy', '143', '14763246470') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Goh Cheng Liang', 'Singapore', 'Industrial', '144', '14717341086') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Philip Anschutz', 'United States', 'Diversified', '145', '14710448664') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sherry Brydson', 'Canada', 'Media & Telecom', '146', '14494602478') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Victor Rashnikov', 'Russian Federation', 'Industrial', '147', '14487292159') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ricardo Salinas', 'Mexico', 'Diversified', '148', '14481087752') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jack Dorsey', 'United States', 'Technology', '149', '14397286931') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Brian Chesky', 'United States', 'Services', '150', '14197358721') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dilip Shanghvi', 'India', 'Health Care', '151', '14189761186') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lui Che-Woo', 'Hong Kong', 'Entertainment', '152', '14133656317') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mikhail Prokhorov', 'Russian Federation', 'Diversified', '153', '14041360789') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lin Jianhua', 'China', 'Technology', '154', '13982610851') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhang Bo', 'China', 'Industrial', '155', '13854647415') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wu Yajun', 'China', 'Real Estate', '156', '13826615498') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Melker Schorling', 'Sweden', 'Diversified', '157', '13761632096') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Charles Schwab', 'United States', 'Finance', '158', '13748253917') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Reinhold Wuerth', 'Germany', 'Industrial', '159', '13664442196') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Li Zhenguo', 'China', 'Energy', '160', '13619503994') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sam Bankman-Fried', 'United States', 'Finance', '161', '13600797502') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jan Koum', 'United States', 'Technology', '162', '13587000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Fan Hongwei', 'China', 'Energy', '163', '13429249533') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Eric Yuan', 'United States', 'Technology', '164', '13404863087') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Charles Ergen', 'United States', 'Media & Telecom', '165', '13384323006') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Savitri Jindal', 'India', 'Commodities', '166', '13342762694') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Leon Black', 'United States', 'Finance', '167', '13166060600') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gong Hongjia', 'China', 'Technology', '168', '13110971989') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Robert Pera', 'United States', 'Technology', '169', '13106376050') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhang Congyuan', 'Taiwan', 'Industrial', '170', '13018249667') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Hugh Grosvenor', 'United Kingdom', 'Real Estate', '171', '12870000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dang Yanbao', 'China', 'Energy', '172', '12598362333') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jorge Moll & family', 'Brazil', 'Health Care', '173', '12343728238') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Kumar Birla', 'India', 'Industrial', '174', '12256597016') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Robin Li', 'China', 'Technology', '175', '12201001787') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ugur Sahin', 'Germany', 'Health Care', '176', '12194568983') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'David Geffen', 'United States', 'Entertainment', '177', '12156150000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'George Roberts', 'United States', 'Finance', '178', '12102401552') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sun Piaoyang', 'China', 'Health Care', '179', '12076380434') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Liu Jincheng', 'China', 'Industrial', '180', '12072217889') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Marijke Mars', 'United States', 'Food & Beverage', '181', '12002429681') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Victoria Mars', 'United States', 'Food & Beverage', '182', '12002429681') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pamela Mars-Wright', 'United States', 'Food & Beverage', '183', '12002429681') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Valerie Mars', 'United States', 'Food & Beverage', '184', '12002429681') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Brian Armstrong', 'United States', 'Technology', '185', '11937408959') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Henry Kravis', 'United States', 'Finance', '186', '11742143518') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sunil Mittal', 'India', 'Media & Telecom', '187', '11734282659') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Joe Gebbia', 'United States', 'Services', '188', '11734139989') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Eyal Ofer', 'Israel', 'Services', '189', '11727829304') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Nathan Blecharczyk', 'United States', 'Services', '190', '11663181115') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Liu Hanyuan', 'China', 'Industrial', '191', '11645529033') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Paolo Rocca & family', 'Italy', 'Commodities', '192', '11585249099') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tobi Lutke', 'Canada', 'Technology', '193', '11574496518') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Raymond Kwok', 'Hong Kong', 'Real Estate', '194', '11476331024') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sarath Ratanavadi', 'Thailand', 'Energy', '195', '11441375984') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Brian Kim', 'Korea, Republic of', 'Technology', '196', '11436045394') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Patrick Collison', 'Ireland', 'Technology', '197', '11362000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Collison', 'Ireland', 'Technology', '198', '11362000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Suleiman Kerimov', 'Russian Federation', 'Commodities', '199', '11352584970') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Marc Benioff', 'United States', 'Technology', '200', '11333446342') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Steven Rales', 'United States', 'Industrial', '201', '11317208067') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jim Davis', 'United States', 'Consumer', '202', '11306147600') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dmitry Rybolovlev', 'Russian Federation', 'Diversified', '203', '11290966661') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alejandro Santo Domingo & family', 'Colombia', 'Food & Beverage', '204', '11288229903') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Qi Shi', 'China', 'Finance', '205', '11236556513') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Rinat Akhmetov', 'Ukraine', 'Industrial', '206', '11232207560') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stan Kroenke', 'United States', 'Real Estate', '207', '11210556400') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pierre Omidyar', 'United States', 'Technology', '208', '11169164010') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Micky Arison', 'United States', 'Entertainment', '209', '11158912022') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Anders Holch Povlsen & family', 'Denmark', 'Retail', '210', '11157382259') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gang Ye', 'Singapore', 'Technology', '211', '11067295934') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Steve Cohen', 'United States', 'Finance', '212', '11053758050') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Antonia Axson Johnson', 'Sweden', 'Industrial', '213', '11048598856') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Thomas Kwok', 'Hong Kong', 'Real Estate', '214', '11027874555') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Cao Renxian', 'China', 'Technology', '215', '11023400874') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Grayken', 'Ireland', 'Finance', '216', '10954518594') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Carl Bennet', 'Sweden', 'Finance', '217', '10885503715') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Heinrich Deichmann & family', 'Germany', 'Retail', '218', '10708343842') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Harry Triguboff', 'Australia', 'Real Estate', '219', '10708000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Carl Cook', 'United States', 'Health Care', '220', '10671343046') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Bobby Murphy', 'United States', 'Technology', '221', '10638944681') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Michael Platt', 'United Kingdom', 'Finance', '222', '10637000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stephane Bancel', 'France', 'Health Care', '223', '10532937568') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dietmar Hopp', 'Germany', 'Technology', '224', '10530254050') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Patrick Soon-Shiong', 'United States', 'Health Care', '225', '10470533396') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Michael Kadoorie', 'Hong Kong', 'Energy', '226', '10449205952') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stan Druckenmiller', 'United States', 'Finance', '227', '10429243993') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Christy Walton', 'United States', 'Retail', '228', '10375524954') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'German Khan', 'Russian Federation', 'Diversified', '229', '10326362441') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gordon Moore', 'United States', 'Technology', '230', '10316253976') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhou Qunfei', 'China', 'Technology', '231', '10301601061') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stefano Pessina', 'Monaco', 'Retail', '232', '10270558684') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jay Y. Lee', 'Korea, Republic of', 'Diversified', '233', '10237402799') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhong Huijuan', 'China', 'Health Care', '234', '10200327200') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Johann Rupert & family', 'South Africa', 'Diversified', '235', '10165366893') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Emmanuel Besnier', 'France', 'Food & Beverage', '236', '10157970380') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'K P Singh', 'India', 'Real Estate', '237', '10070119971') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Liu Yongxing', 'China', 'Industrial', '238', '10049754117') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jin Baofang', 'China', 'Energy', '239', '10030566917') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Qian Dongqi', 'China', 'Technology', '240', '10009552727') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Rocco Commisso', 'United States', 'Media & Telecom', '241', '9994639802') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Albert Sobrato', 'United States', 'Real Estate', '242', '9970000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gianluigi Aponte', 'Switzerland', 'Services', '243', '9949070723') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Evan Spiegel', 'United States', 'Technology', '244', '9947006401') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Fredriksen', 'Cyprus', 'Industrial', '245', '9918522421') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ding Shizhong', 'China', 'Consumer', '246', '9914754218') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Chen Zhiping', 'China', 'Consumer', '247', '9905101791') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Les Wexner', 'United States', 'Retail', '248', '9834736708') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Li Ge', 'United States', 'Health Care', '249', '9826171311') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Leonid Fedun', 'Russian Federation', 'Energy', '250', '9818706622') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Izzy Englander', 'United States', 'Finance', '251', '9790899001') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Laurent Dassault', 'France', 'Diversified', '252', '9751753060') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Marie-Helene Habert-Dassault', 'France', 'Diversified', '253', '9751753060') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Thierry Dassault', 'France', 'Diversified', '254', '9751753060') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Marcel Telles', 'Brazil', 'Food & Beverage', '255', '9749828578') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jerry Jones', 'United States', 'Entertainment', '256', '9747496433') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Graeme Hart', 'New Zealand', 'Finance', '257', '9708792695') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Liu Yonghao', 'China', 'Diversified', '258', '9682352418') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wee Cho Yaw', 'Singapore', 'Finance', '259', '9652215618') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Malone', 'United States', 'Media & Telecom', '260', '9615995110') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ding Shijia', 'China', 'Consumer', '261', '9528698336') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alberto Bailleres', 'Mexico', 'Commodities', '262', '9524245290') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andy Beal', 'United States', 'Finance', '263', '9514395523') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Patrick Drahi', 'France', 'Media & Telecom', '264', '9500260128') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Li Ping', 'China', 'Industrial', '265', '9490072662') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Niels Louis-Hansen', 'Denmark', 'Health Care', '266', '9434803961') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'August von Finck', 'Germany', 'Diversified', '267', '9396917881') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Georg Schaeffler', 'Germany', 'Industrial', '268', '9372585369') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tim Sweeney', 'United States', 'Technology', '269', '9372000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Theo Albrecht Jr', 'Germany', 'Retail', '270', '9309746632') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Blair Parry-Okeden', 'United States', 'Media & Telecom', '271', '9251991189') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jim Kennedy', 'United States', 'Media & Telecom', '272', '9251991189') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alexander Abramov', 'Russian Federation', 'Industrial', '273', '9247679349') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Rupert Murdoch', 'United States', 'Media & Telecom', '274', '9185699425') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Silvio Berlusconi', 'Italy', 'Media & Telecom', '275', '9181602551') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Magdalena Martullo', 'Switzerland', 'Industrial', '276', '9125027635') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Luis Sarmiento', 'Colombia', 'Finance', '277', '9070116323') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'George Lucas', 'United States', 'Entertainment', '278', '9048575525') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Hansjoerg Wyss', 'Switzerland', 'Health Care', '279', '9016120351') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'David Thomson', 'Canada', 'Media & Telecom', '280', '8978581065') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Taylor Thomson', 'Canada', 'Media & Telecom', '281', '8977838847') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Peter Thomson', 'Canada', 'Media & Telecom', '282', '8977838847') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mitchell Rales', 'United States', 'Industrial', '283', '8960870218') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'David Sun', 'United States', 'Technology', '284', '8932525000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Tu', 'United States', 'Technology', '285', '8932525000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Samuel Yin', 'Taiwan', 'Diversified', '286', '8926026397') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Joseph Tsai', 'Canada', 'Technology', '287', '8883417753') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Rahel Blocher', 'Switzerland', 'Industrial', '288', '8850686499') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Giorgio Armani', 'Italy', 'Consumer', '289', '8781135126') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Anthony von Mandl', 'Canada', 'Consumer', '290', '8760050400') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Nusli Wadia', 'India', 'Diversified', '291', '8731682199') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Reinhold Schmieding', 'United States', 'Health Care', '292', '8712465580') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Li Shuirong', 'China', 'Energy', '293', '8655067510') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Robert Smith', 'United States', 'Finance', '294', '8650000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Iskandar Makhmudov', 'Russian Federation', 'Commodities', '295', '8648730163') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Benu Bangur', 'India', 'Commodities', '296', '8628196269') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Laisheng', 'China', 'Industrial', '297', '8610250732') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Michael Otto', 'Germany', 'Retail', '298', '8608798397') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andy Bechtolsheim', 'Germany', 'Technology', '299', '8577915749') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Rahul Bajaj', 'India', 'Diversified', '300', '8549214768') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Yu Yong', 'China', 'Finance', '301', '8543818019') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pham Nhat Vuong', 'Viet Nam', 'Real Estate', '302', '8535574406') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sandra Ortega Mera', 'Spain', 'Retail', '303', '8454332513') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Xavier Niel', 'France', 'Technology', '304', '8440025070') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Carlos Sicupira', 'Brazil', 'Food & Beverage', '305', '8437427351') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tammy Gustavson', 'United States', 'Services', '306', '8428581319') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Anthony Pratt', 'Australia', 'Industrial', '307', '8406266519') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'James Pattison', 'Canada', 'Media & Telecom', '308', '8400006129') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stephen Ross', 'United States', 'Real Estate', '309', '8386000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mat Ishbia', 'United States', 'Finance', '310', '8384476669') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vincent Bollore', 'France', 'Diversified', '311', '8381661250') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Shigenobu Nagamori', 'Japan', 'Industrial', '312', '8357087999') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jude Reyes', 'United States', 'Consumer', '313', '8353350000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Chris Reyes', 'United States', 'Consumer', '314', '8353350000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ernest Garcia III', 'United States', 'Consumer', '315', '8330051794') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Chen Jianhua', 'China', 'Industrial', '316', '8329331905') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Richard Kinder', 'United States', 'Energy', '317', '8322597816') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Martin Viessmann & family', 'Germany', 'Industrial', '318', '8322470391') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Oleg Tinkov', 'Russian Federation', 'Finance', '319', '8319504615') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Cen Junda', 'China', 'Health Care', '320', '8297338458') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Cai Kui', 'China', 'Real Estate', '321', '8295381963') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Doerr', 'United States', 'Finance', '322', '8281377732') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wu Shaoxun', 'China', 'Food & Beverage', '323', '8279068983') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jian Jun', 'China', 'Consumer', '324', '8247549275') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Chase Coleman', 'United States', 'Finance', '325', '8243920722') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ned Johnson IV', 'United States', 'Finance', '326', '8240275499') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Elizabeth Johnson', 'United States', 'Finance', '327', '8240275499') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Nicky Oppenheimer', 'South Africa', 'Diversified', '328', '8225000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Xu Shihui', 'China', 'Food & Beverage', '329', '8209328960') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Michael Rubin', 'United States', 'Retail', '330', '8191000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tatyana Bakalchuk', 'Russian Federation', 'Technology', '331', '8189393578') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Liz Mohn', 'Germany', 'Media & Telecom', '332', '8176503948') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gabe Newell', 'United States', 'Technology', '333', '8166902003') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ronda Stryker', 'United States', 'Health Care', '334', '8155766395') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Jianlin', 'China', 'Real Estate', '335', '8147755776') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Johann Graf', 'Austria', 'Entertainment', '336', '8140673047') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhao Yan', 'China', 'Health Care', '337', '8133860474') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Josh Harris', 'United States', 'Finance', '338', '8118522530') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andrey Guryev', 'Russian Federation', 'Industrial', '339', '8081718347') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Cheng Xue', 'China', 'Food & Beverage', '340', '8078277474') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dennis Washington', 'United States', 'Industrial', '341', '8047015030') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Frederik Paulsen', 'Sweden', 'Health Care', '342', '8036386754') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'He Xiaopeng', 'China', 'Technology', '343', '8002854521') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ralph Lauren', 'United States', 'Consumer', '344', '7988152448') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Laichun', 'China', 'Industrial', '345', '7985210732') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Yao Liangsong', 'China', 'Retail', '346', '7946899514') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Frank Lowy', 'Australia', 'Real Estate', '347', '7925000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'John Sall', 'United States', 'Technology', '348', '7910976721') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Steven Spielberg', 'United States', 'Entertainment', '349', '7900000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Charles Butt & family', 'United States', 'Retail', '350', '7883288324') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lin Bin', 'United States', 'Technology', '351', '7856888954') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Laurence Graff', 'United Kingdom', 'Consumer', '352', '7826949735') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Leng You-Bin', 'China', 'Consumer', '353', '7802104205') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alexey Kuzmichev', 'Russian Federation', 'Diversified', '354', '7794419740') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Shari Arison', 'Israel', 'Diversified', '355', '7687292698') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Horst Pudwill', 'Germany', 'Consumer', '356', '7658367847') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Guillaume Pousaz', 'Switzerland', 'Technology', '357', '7650000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Shahid Khan', 'United States', 'Consumer', '358', '7634100580') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Juan Beckmann Vidal & family', 'Mexico', 'Food & Beverage', '359', '7629332634') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Takahisa Takahara', 'Japan', 'Consumer', '360', '7619891610') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Hui Ka Yan', 'China', 'Real Estate', '361', '7560167267') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mohammed Al Amoudi', 'Saudi Arabia', 'Energy', '362', '7523341696') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'George Soros', 'United States', 'Finance', '363', '7500000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andre Hoffmann', 'Switzerland', 'Health Care', '364', '7493566382') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Seo Jung-Jin', 'Korea, Republic of', 'Health Care', '365', '7482060281') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alain Merieux', 'France', 'Health Care', '366', '7463293689') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Terry Pegula', 'United States', 'Energy', '367', '7463080310') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jorn Rausing', 'Sweden', 'Services', '368', '7451206990') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'German Larrea', 'Mexico', 'Commodities', '369', '7437376187') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Yusuo', 'China', 'Energy', '370', '7411000678') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dan Cathy', 'United States', 'Food & Beverage', '371', '7394222606') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Bubba Cathy', 'United States', 'Food & Beverage', '372', '7394222606') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Stef Wertheimer', 'Israel', 'Diversified', '373', '7375000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Anthony Bamford & family', 'United Kingdom', 'Industrial', '374', '7373770966') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Nancy Laurie', 'United States', 'Retail', '375', '7370730917') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tito Beveridge', 'United States', 'Consumer', '376', '7369358810') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Natie Kirsh', 'South Africa', 'Food & Beverage', '377', '7364969447') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Manuel Villar', 'Philippines', 'Diversified', '378', '7333211050') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Axel Oberwelland', 'Germany', 'Food & Beverage', '379', '7330344636') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Teh Hong Piow', 'Malaysia', 'Finance', '380', '7324032654') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'David Shaw', 'United States', 'Finance', '381', '7312833705') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sergey Gordeev', 'Russian Federation', 'Real Estate', '382', '7274370921') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lu Weiding', 'China', 'Diversified', '383', '7253241880') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tom Gores', 'United States', 'Finance', '384', '7215000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Yu Renrong', 'China', 'Technology', '385', '7206811616') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ludwig Merckle', 'Germany', 'Industrial', '386', '7202903619') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Randa Williams', 'United States', 'Energy', '387', '7163950421') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Dannine Avara', 'United States', 'Energy', '388', '7159293861') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Scott Duncan', 'United States', 'Energy', '389', '7159293861') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Bob Rich', 'United States', 'Food & Beverage', '390', '7152924300') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vyacheslav Kantor', 'Russian Federation', 'Industrial', '391', '7137018556') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Milane Frantz', 'United States', 'Energy', '392', '7135423861') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Chris Hohn', 'United Kingdom', 'Finance', '393', '7117630000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Peter Thiel', 'United States', 'Finance', '394', '7098532701') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Alexander Otto', 'Germany', 'Real Estate', '395', '7080257223') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gwendolyn Sontheim Meyer', 'United States', 'Commodities', '396', '7075072722') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pauline Keinath', 'United States', 'Commodities', '397', '7075072722') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Linda Campbell', 'Canada', 'Media & Telecom', '398', '7064730464') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gaye Farncombe', 'Canada', 'Media & Telecom', '399', '7064730464') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Peter-Alexander Wacker & family', 'Germany', 'Industrial', '400', '7053209683') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Chip Wilson', 'Canada', 'Retail', '401', '7033343715') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lynn Schusterman', 'United States', 'Energy', '402', '7029128359') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jon Gray', 'United States', 'Finance', '403', '7024313211') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Patrick Ryan', 'United States', 'Services', '404', '7014423553') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Reed Hastings', 'United States', 'Technology', '405', '7007248845') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mark Shoen', 'United States', 'Services', '406', '6991592589') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jane Lauder', 'United States', 'Consumer', '407', '6962438875') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ruan Liping', 'China', 'Industrial', '408', '6959928059') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Maja Hoffmann', 'Switzerland', 'Health Care', '409', '6958925985') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vera Michalski-Hoffmann', 'Switzerland', 'Health Care', '410', '6958406389') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ruan Xueping', 'China', 'Industrial', '411', '6934928059') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Fredrik Lundberg', 'Sweden', 'Real Estate', '412', '6933711197') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Geoffrey Kwok', 'Hong Kong', 'Real Estate', '413', '6915164116') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Nassef Sawiris', 'Egypt', 'Industrial', '414', '6907952456') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Yeung Kin-Man', 'Hong Kong', 'Technology', '415', '6890908362') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ashwin Dani & family', 'India', 'Industrial', '416', '6862761835') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Joseph Lau', 'Hong Kong', 'Real Estate', '417', '6851496721') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Steve Feinberg', 'United States', 'Finance', '418', '6806472000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Gao Dekang', 'China', 'Consumer', '419', '6805584269') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Vyacheslav Kim', 'Kazakhstan', 'Finance', '420', '6804086304') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Edward Roski', 'United States', 'Real Estate', '421', '6775000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'David Reuben', 'United Kingdom', 'Diversified', '422', '6750000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ivan Glasenberg', 'Australia', 'Commodities', '423', '6745620687') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Simon Reuben', 'United Kingdom', 'Diversified', '424', '6725000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ronald McAulay', 'Hong Kong', 'Energy', '425', '6716281915') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Petr Aven', 'Russian Federation', 'Diversified', '426', '6706775722') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Frank Wang', 'China', 'Technology', '427', '6695667084') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Nik Storonsky', 'United Kingdom', 'Finance', '428', '6686000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Olav Thon', 'Norway', 'Real Estate', '429', '6675046760') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Marc Rowan', 'United States', 'Finance', '430', '6670321276') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Henry Samueli', 'United States', 'Technology', '431', '6660526783') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Hiroshi Mikitani', 'Japan', 'Retail', '432', '6647795733') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'J K Irving', 'Canada', 'Commodities', '433', '6630106813') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Idan Ofer', 'Israel', 'Energy', '434', '6625442626') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Denis Sverdlov', 'Russian Federation', 'Technology', '435', '6584861275') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lai Meisong', 'China', 'Services', '436', '6569494671') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Su Hua', 'China', 'Technology', '437', '6546293881') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Zhang Lei', 'China', 'Finance', '438', '6539761285') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mikheil Lomtadze', 'Georgia', 'Finance', '439', '6534099787') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'David Bonderman', 'United States', 'Finance', '440', '6528754137') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mahendra Choksi & family', 'India', 'Industrial', '441', '6511190524') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Marcos Galperin', 'Argentina', 'Technology', '442', '6500000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Charles Cadogan', 'United Kingdom', 'Real Estate', '443', '6487000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Joe Lewis', 'United Kingdom', 'Diversified', '444', '6485290966') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jean-Pierre Cayard', 'France', 'Food & Beverage', '445', '6464786537') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tony Ressler', 'United States', 'Finance', '446', '6436676371') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Kenneth Dart', 'Cayman Islands', 'Finance', '447', '6428167121') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Bin Li', 'China', 'Technology', '448', '6402883596') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Matthew Prince', 'United States', 'Technology', '449', '6400580505') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Kjeld Kirk Kristiansen', 'Denmark', 'Consumer', '450', '6375292269') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Hui Wing Mau', 'Hong Kong', 'Real Estate', '451', '6358168325') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lin Muqin', 'China', 'Consumer', '452', '6353456912') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tsai Eng-Meng', 'Taiwan', 'Food & Beverage', '453', '6351889078') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mike Novogratz', 'United States', 'Finance', '454', '6339175263') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ann Kroenke', 'United States', 'Retail', '455', '6338649917') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Kim Jung-Ju', 'Korea, Republic of', 'Technology', '456', '6335211394') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Abhay Vakil & family', 'India', 'Industrial', '457', '6304967389') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tom Morris', 'United Kingdom', 'Retail', '458', '6298143811') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Leonard Stern', 'United States', 'Real Estate', '459', '6269144273') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ray Hunt', 'United States', 'Energy', '460', '6267739006') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jean-Michel Besnier', 'France', 'Food & Beverage', '461', '6266785490') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Kei Hoi Pang', 'China', 'Real Estate', '462', '6248173396') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Pat Stryker', 'United States', 'Health Care', '463', '6246311790') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sam Zell', 'United States', 'Real Estate', '464', '6217003143') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Denise Coates', 'United Kingdom', 'Entertainment', '465', '6207778724') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Ken Fisher', 'United States', 'Finance', '466', '6206397000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'M A Yusuff Ali', 'United Arab Emirates', 'Food & Beverage', '467', '6194561102') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Terry Gou', 'Taiwan', 'Industrial', '468', '6162667431') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Johan Johannson & family', 'Norway', 'Retail', '469', '6161442342') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Agnete Kirk Thinggaard', 'Denmark', 'Consumer', '470', '6150298714') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Thomas Kirk Kristiansen', 'Denmark', 'Consumer', '471', '6150298714') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Sofie Kirk Kristiansen', 'Denmark', 'Consumer', '472', '6150292269') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Henry Laufer', 'United States', 'Finance', '473', '6150000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Katharine Rayner', 'United States', 'Media & Telecom', '474', '6125932633') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jeffery Hildebrand', 'United States', 'Energy', '475', '6116041227') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Margaretta Taylor', 'United States', 'Media & Telecom', '476', '6115932633') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'James Cox Chambers', 'United States', 'Media & Telecom', '477', '6115932633') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Eric Smidt', 'United States', 'Retail', '478', '6115910000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Barry Lam', 'Taiwan', 'Technology', '479', '6109500049') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Martin Lorentzon', 'Sweden', 'Technology', '480', '6091712276') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Yanqing', 'China', 'Technology', '481', '6079421942') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Andreas Halvorsen', 'Norway', 'Finance', '482', '6078281010') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Antti Herlin', 'Finland', 'Industrial', '483', '6069556494') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Anthony Wood', 'United States', 'Technology', '484', '6064770104') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Tony James', 'United States', 'Finance', '485', '6064565309') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Richard Branson', 'United Kingdom', 'Diversified', '486', '6053880827') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Bidzina Ivanishvili', 'Georgia', 'Diversified', '487', '6045000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Joe Mansueto', 'United States', 'Technology', '488', '6023420861') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Kjell Inge Rokke', 'Norway', 'Industrial', '489', '6020669126') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Richard Li', 'Hong Kong', 'Media & Telecom', '490', '6001660142') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Barry Diller', 'United States', 'Technology', '491', '5996943007') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Robert Kraft', 'United States', 'Entertainment', '492', '5992278736') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Majid Al Futtaim', 'United Arab Emirates', 'Real Estate', '493', '5958837430') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Trevor Rees-Jones', 'United States', 'Energy', '494', '5956053710') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Mark Cuban', 'United States', 'Technology', '495', '5951000000') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Jiang Bin', 'China', 'Technology', '496', '5937418003') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Frits Goldschmeding', 'Netherlands', 'Retail', '497', '5935283520') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Lin Li', 'China', 'Diversified', '498', '5893586923') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Wang Wenjing', 'China', 'Technology', '499', '5891364144') ;
INSERT INTO t_top_five_hundred  ( commonname, citizenship, industry, rank, worth)  VALUES  ( 'Cliff Obrecht', 'Australia', 'Services', '500', '5890000000') ;

